name: deploy

on:
  push:
    branches: [ deploy ]
  workflow_dispatch:

permissions:
  contents: read

env:
  APPLICATION_URL_PROD: https://applepay.martincostello.com
  AZURE_WEBAPP_NAME: applepaymartincostello
  AZURE_WEBAPP_PACKAGE_PATH: ./artifacts
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_GENERATE_ASPNET_CERTIFICATE: false
  DOTNET_MULTILEVEL_LOOKUP: 0
  DOTNET_NOLOGO: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  NUGET_XMLDOC_MODE: skip

jobs:
  build:
    name: build
    runs-on: windows-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3

    - name: Build and publish
      shell: pwsh
      run: ./build.ps1 -SkipTests -Runtime win-x64

    - name: Publish artifacts
      uses: actions/upload-artifact@v4
      with:
        name: webapp
        path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

  deploy:
    name: deploy-production
    needs: build
    runs-on: windows-latest
    concurrency: production_environment

    environment:
      name: production
      url: ${{ env.APPLICATION_URL_PROD }}

    permissions:
      id-token: write

    steps:

    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: webapp

    - name: Azure log in
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Deploy to Azure App Service
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
